import Head from "next/head";
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

import ContactUsPosition from "@/components/ContactUs";
import Header from '@/components/home/Header';
import CarouselPartners from '@/components/CarouselPartners/CarouselPartners';
import AboutUs from '@/components/home/AboutUs';
import OurProjects from '@/components/OurProjects';
import Services from '@/components/home/Services';
import Scroll from '@/components/home/Scroll';
import Startap from '@/components/home/Startap';
import News from '@/components/home/News';
import ContactUs from '@/components/home/ContactUs';
import Corousel from '@/components/Carousel';


export async function getServerSideProps({ locale }) {
  return {
    props: {
      ... (await serverSideTranslations(locale, ['common',])),
      locale: locale
    },
  };
}

export default function Home({ locale }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <ContactUsPosition/> */}
      <Header locale={locale} />
      <CarouselPartners />
      <AboutUs />
      <OurProjects />
      <Services />
      <Scroll />
      <Startap />
      <News />
      <ContactUs />
      <Corousel/>
    </>
  );
}
