import Head from "next/head";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { Toaster } from 'react-hot-toast';

import Header from "@/components/home/Header";
import CarouselPartners from "@/components/CarouselPartners/CarouselPartners";
import AboutUs from "@/components/home/AboutUs";
import OurProjects from "@/components/OurProjects";
import Services from "@/components/home/Services";
import Scroll from "@/components/home/Scroll";
import Startap from "@/components/home/Startap";
import News from "@/components/home/News";
import ContactUs from "@/components/home/ContactUs";
import Carousel from "@/components/Carousel";
// import { motion } from "framer-motion";
// import { axiosT } from "@/api/axios";
// import { useEffect } from "react";

import { getAllServicesList } from "@/api/pagesApis/service";
import {
  getMainPageProjects,
  getProjects,
  getStartUpProjects,
} from "@/api/pagesApis/project";

import { getAboutUs } from "@/api/pagesApis/aboutUs";

export async function getServerSideProps({ locale }) {
  const serviceList = await getAllServicesList(locale);
  const startups = await getStartUpProjects(locale);
  const projects = await getMainPageProjects(locale, { p: 1, page_size: 5 });
  const aboutUs = await getAboutUs(locale);

  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"])),
      locale: locale,
      serviceList,
      startups,
      projects,
      aboutUs,
    },
  };
}

export default function Home({ serviceList, startups, projects, aboutUs }) {
  return (
    <>
      <Head>
        <title>Technocorp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <Header />
      <CarouselPartners />

      <AboutUs aboutUs={aboutUs} />

      <OurProjects projects={projects} />

      <Services services={serviceList} />
      <Scroll />
      <Startap startups={startups} />
      <News />
      <ContactUs />
      <Carousel />
      <Toaster
        position="top-right"
        toastOptions={{
          style: {
            background: '#363636',
            color: '#fff',
            fontFamily: "Roboto-Medium",
            fontSize: "1.8rem",
          },
        }}
      />

    </>
  );
}
