import Head from "next/head";
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

// import styles from "@/styles/styles.module.css";

// import ContactUsPosition from "@/components/ContactUs";
import Header from '@/components/home/Header';
import CarouselPartners from '@/components/CarouselPartners/CarouselPartners';
import AboutUs from '@/components/home/AboutUs';
import OurProjects from '@/components/OurProjects';
import Services from '@/components/home/Services';
import Scroll from '@/components/home/Scroll';
import Startap from '@/components/home/Startap';
import News from '@/components/home/News';
import ContactUs from '@/components/home/ContactUs';
import Carousel from '@/components/Carousel';
// import СircularShadow from '@/components/СircularShadow';


export async function getServerSideProps({ locale }) {
  return {
    props: {
      ... (await serverSideTranslations(locale, ['common',])),
      locale: locale
    },
  };
}

export default function Home({ locale }) {
  return (
    <>
      <Head>
        <title>Technocor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      {/* <ContactUsPosition/> */}
      <Header />
      <CarouselPartners />
      {/* <СircularShadow /> */}
      < AboutUs />
      <OurProjects />
      <Services />
      <Scroll />
      <Startap />
      <News />
      <ContactUs />
      <Carousel />

    </>

  );
}
